version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: loan_app_db
    environment:
      POSTGRES_USER: loanapp
      POSTGRES_PASSWORD: loanapp123
      POSTGRES_DB: loanapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
